name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest
    - name: clone xtl
      run: git clone https://github.com/xtensor-stack/xtl
    - name: clone xtensor
      run: git clone https://github.com/xtensor-stack/xtensor
    - name: compile
      run: bash compile.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        path: FissionOpt.wasm
        if-no-files-found: error  
        retention-days: 1
