name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest
    - name: clone xtl
      run: git clone https://github.com/xtensor-stack/xtl
    - name: clone
      run: git clone https://github.com/xtensor-stack/xtensor
    - name: compile
      run: bash compile.sh
